XML.Company/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace XML.Company.Models
{
    public class Invoice
    {
        [Key]
        public int Id { get; set; }
        public string MessageId { get; set; }

        public string SupplierName { get; set; }

        public string SupplierAddress { get; set; }

        public string PIBSupplier { get; set; }

        public string BuyerName { get; set; }

        public string BuyerAddress { get; set; }

        public string BuyerAccount { get; set; }

        public string BillingDate { get; set; }

        public string GoodsValue { get; set; }

        public string  ServicePrice { get; set; }
    }
}

XML.Company/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using XML.Company.ConnectedServices.BankServiceReference;

namespace XML.Company.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBankService _bankService;

        public HomeController(IBankService bankService)
        {
            _bankService = bankService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            var response = _bankService.PaymentActionAsync(new PaymentActionRequest1()).Result;
            var response2 = _bankService.GetAccountStatementAsync(new GetAccountStatementRequest()).Result;
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

XML.Company/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using XML.Company.Models;

namespace XML.Company.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly XMLCompanyContext _context;

        public InvoicesController()
        {
            //_context = context;    
        }

        // GET: Invoices
        public async Task<IActionResult> Index()
        {
            var model = new List<Invoice>()
            {
                new Invoice()
                {
                    BuyerName = "Ivan"
                },

                new Invoice()
                {
                    BuyerName = "Luka"
                }
            };
            return PartialView(model);
        }

        // GET: Invoices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .SingleOrDefaultAsync(m => m.Id == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: Invoices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MessageId,SupplierName,SupplierAddress,PIBSupplier,BuyerName,BuyerAddress,BuyerAccount,BillingDate,GoodsValue,ServicePrice")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invoice);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice.SingleOrDefaultAsync(m => m.Id == id);
            if (invoice == null)
            {
                return NotFound();
            }
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MessageId,SupplierName,SupplierAddress,PIBSupplier,BuyerName,BuyerAddress,BuyerAccount,BillingDate,GoodsValue,ServicePrice")] Invoice invoice)
        {
            if (id != invoice.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .SingleOrDefaultAsync(m => m.Id == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoice = await _context.Invoice.SingleOrDefaultAsync(m => m.Id == id);
            _context.Invoice.Remove(invoice);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool InvoiceExists(int id)
        {
            return _context.Invoice.Any(e => e.Id == id);
        }
    }
}

XML.Company/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<input  class="form-group-lg"/> 
<input type="submit" class="btn btn-success" value="Send Invoice" />


<p>Use this area to provide additional information.</p>

XML.Company/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

XML.Company/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

XML.Company/Views/Invoices/Create.cshtml
@model XML.Company.Models.Invoice

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="MessageId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MessageId" class="form-control" />
                <span asp-validation-for="MessageId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SupplierName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SupplierAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SupplierAddress" class="form-control" />
                <span asp-validation-for="SupplierAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PIBSupplier" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PIBSupplier" class="form-control" />
                <span asp-validation-for="PIBSupplier" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerName" class="form-control" />
                <span asp-validation-for="BuyerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerAddress" class="form-control" />
                <span asp-validation-for="BuyerAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerAccount" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerAccount" class="form-control" />
                <span asp-validation-for="BuyerAccount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BillingDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BillingDate" class="form-control" />
                <span asp-validation-for="BillingDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="GoodsValue" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="GoodsValue" class="form-control" />
                <span asp-validation-for="GoodsValue" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ServicePrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ServicePrice" class="form-control" />
                <span asp-validation-for="ServicePrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

XML.Company/Views/Invoices/Delete.cshtml
@model XML.Company.Models.Invoice

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Home/Index.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.MessageId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MessageId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SupplierAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SupplierAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PIBSupplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PIBSupplier)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerAccount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerAccount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GoodsValue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GoodsValue)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

XML.Company/Views/Invoices/Details.cshtml
@model XML.Company.Models.Invoice

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Home/Index.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MessageId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MessageId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SupplierAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SupplierAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PIBSupplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PIBSupplier)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuyerAccount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuyerAccount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GoodsValue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GoodsValue)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

XML.Company/Views/Invoices/Edit.cshtml
@model XML.Company.Models.Invoice

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Home/Index.cshtml";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="MessageId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="MessageId" class="form-control" />
                <span asp-validation-for="MessageId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SupplierName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SupplierAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SupplierAddress" class="form-control" />
                <span asp-validation-for="SupplierAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PIBSupplier" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PIBSupplier" class="form-control" />
                <span asp-validation-for="PIBSupplier" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerName" class="form-control" />
                <span asp-validation-for="BuyerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerAddress" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerAddress" class="form-control" />
                <span asp-validation-for="BuyerAddress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BuyerAccount" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BuyerAccount" class="form-control" />
                <span asp-validation-for="BuyerAccount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BillingDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BillingDate" class="form-control" />
                <span asp-validation-for="BillingDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="GoodsValue" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="GoodsValue" class="form-control" />
                <span asp-validation-for="GoodsValue" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ServicePrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ServicePrice" class="form-control" />
                <span asp-validation-for="ServicePrice" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

XML.Company/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XML.Company</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">XML.Company</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - XML.Company</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>